spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bangbangtuan_outsourcing?serverTimezone=Asia/Shanghai
    username: root
    password: 59080125
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
server:
  port: 9090


debug: true
